@echo off
setlocal

set ROOT=E:\RustDesk
set DIST=%ROOT%\flutter\build\windows\x64\runner\Release
set APP_NAME=Gubernia Desktop

call "C:\Users\stepanow.GUBERNIA\.rustdesk-build-tools\VSBuildTools\Common7\Tools\VsDevCmd.bat" -arch=x64
if errorlevel 1 exit /b 1

set "APPDATA=%ROOT%\.codex_tool_state\AppData\Roaming"
set "LOCALAPPDATA=%ROOT%\.codex_tool_state\AppData\Local"

rem Reset autogenerated MSI fragments to avoid duplicate components on repeated runs
git -C "%ROOT%" checkout -- res/msi/Package/Components/RustDesk.wxs res/msi/Package/Includes.wxi res/msi/Package/Components/Regs.wxs >nul 2>&1

if not exist "%DIST%\rustdesk.exe" (
  echo ERROR: %DIST%\rustdesk.exe not found. Build Windows release first.
  exit /b 1
)

copy /Y "%DIST%\rustdesk.exe" "%DIST%\%APP_NAME%.exe" >nul
if errorlevel 1 exit /b 1

python "%ROOT%\res\msi\preprocess.py" --app-name "%APP_NAME%" --arp -d "%DIST%"
if errorlevel 1 exit /b 1

"C:\Users\stepanow.GUBERNIA\.rustdesk-build-tools\nuget.exe" restore "%ROOT%\res\msi\msi.sln"
if errorlevel 1 exit /b 1

msbuild "%ROOT%\res\msi\msi.sln" -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10 /p:Cultures=ru-ru
if errorlevel 1 exit /b 1

echo.
echo MSI ready:
echo %ROOT%\res\msi\Package\bin\x64\Release\ru-ru\Package.msi
exit /b 0
